mission=
{
	["coalition"]=
	{
		["blue"]=
		{
			["bullseye"]=
			{
				["x"]=-291014,
				["y"]=617414
			},
			["country"]=
			{
				[1]=
				{
					["id"]=21,
					["name"]="Australia"
				},
				[10]=
				{
					["id"]=15,
					["name"]="Israel"
				},
				[11]=
				{
					["id"]=20,
					["name"]="Italy"
				},
				[12]=
				{
					["id"]=12,
					["name"]="Norway"
				},
				[13]=
				{
					["id"]=40,
					["name"]="Poland"
				},
				[14]=
				{
					["id"]=45,
					["name"]="South Korea"
				},
				[15]=
				{
					["id"]=9,
					["name"]="Spain"
				},
				[16]=
				{
					["id"]=10,
					["name"]="The Netherlands"
				},
				[17]=
				{
					["id"]=3,
					["name"]="Turkey"
				},
				[18]=
				{
					["id"]=4,
					["name"]="UK"
				},
				[19]=
				{
					["id"]=2,
					["name"]="USA",
					["plane"]=
					{
						["group"]=
						{
							[1]=
							{
								["communication"]=true,
								["frequency"]=251,
								["groupId"]=2,
								["hidden"]=false,
								["modulation"]=0,
								["name"]="DictKey_Translation_7",
								["radioSet"]=false,
								["route"]=
								{
									["points"]=
									{
										[1]=
										{
											["ETA"]=0,
											["ETA_locked"]=true,
											["action"]="From Parking Area Hot",
											["alt"]=0,
											["alt_type"]="BARO",
											["formation_template"]="",
											["helipadId"]=1,
											["linkUnit"]=1,
											["name"]="",
											["properties"]=
											{
												["angle"]=0,
												["scale"]=0,
												["steer"]=2,
												["vangle"]=0,
												["vnav"]=0
											},
											["speed"]=0,
											["speed_locked"]=true,
											["task"]=
											{
												["id"]="ComboTask",
												["params"]=
												{
													["tasks"]=
													{
														[1]=
														{
															["auto"]=true,
															["enabled"]=true,
															["id"]="EngageTargets",
															["key"]="CAP",
															["number"]=1,
															["params"]=
															{
																["priority"]=0,
																["targetTypes"]=
																{
																	[1]="Air"
																}
															}
														},
														[2]=
														{
															["auto"]=false,
															["enabled"]=true,
															["id"]="WrappedAction",
															["number"]=2,
															["params"]=
															{
																["action"]=
																{
																	["id"]="EPLRS",
																	["params"]=
																	{
																		["groupId"]=1,
																		["value"]=true
																	}
																}
															}
														}
													}
												}
											},
											["type"]="TakeOffParkingHot",
											["x"]=-214496.46875,
											["y"]=412218.921875
										},
										[2]=
										{
											["ETA"]=0,
											["ETA_locked"]=false,
											["action"]="Turning Point",
											["alt"]=2438.4,
											["alt_type"]="BARO",
											["formation_template"]="",
											["name"]="",
											["properties"]=
											{
												["angle"]=0,
												["scale"]=0,
												["steer"]=2,
												["vangle"]=0,
												["vnav"]=0
											},
											["speed"]=166.6666666666667,
											["speed_locked"]=true,
											["task"]=
											{
												["id"]="ComboTask",
												["params"]=
												{
													["tasks"]=
													{
													}
												}
											},
											["type"]="Turning Point",
											["x"]=-213496.46875,
											["y"]=415218.921875
										},
										[3]=
										{
											["ETA"]=0,
											["ETA_locked"]=false,
											["action"]="Turning Point",
											["alt"]=7924.8,
											["alt_type"]="BARO",
											["formation_template"]="",
											["name"]="",
											["properties"]=
											{
												["angle"]=0,
												["scale"]=0,
												["steer"]=2,
												["vangle"]=0,
												["vnav"]=0
											},
											["speed"]=166.6666666666667,
											["speed_locked"]=true,
											["task"]=
											{
												["id"]="ComboTask",
												["params"]=
												{
													["tasks"]=
													{
													}
												}
											},
											["type"]="Turning Point",
											["x"]=-141328.311297364,
											["y"]=484441.4402479365
										},
										[4]=
										{
											["ETA"]=0,
											["ETA_locked"]=false,
											["action"]="Turning Point",
											["alt"]=7924.8,
											["alt_type"]="BARO",
											["formation_template"]="",
											["name"]="",
											["properties"]=
											{
												["angle"]=0,
												["scale"]=0,
												["steer"]=2,
												["vangle"]=0,
												["vnav"]=0
											},
											["speed"]=166.6666666666667,
											["speed_locked"]=true,
											["task"]=
											{
												["id"]="ComboTask",
												["params"]=
												{
													["tasks"]=
													{
													}
												}
											},
											["type"]="Turning Point",
											["x"]=-165218.15032452636,
											["y"]=461526.6966912706
										},
										[5]=
										{
											["ETA"]=0,
											["ETA_locked"]=false,
											["action"]="Landing",
											["airdromeId"]=1,
											["alt"]=0,
											["alt_type"]="BARO",
											["formation_template"]="",
											["name"]="",
											["properties"]=
											{
												["angle"]=0,
												["scale"]=0,
												["steer"]=2,
												["vangle"]=0,
												["vnav"]=0
											},
											["speed"]=0,
											["speed_locked"]=true,
											["task"]=
											{
												["id"]="ComboTask",
												["params"]=
												{
													["tasks"]=
													{
													}
												}
											},
											["type"]="Land",
											["x"]=-214496.46875,
											["y"]=412218.921875
										}
									}
								},
								["start_time"]=0,
								["task"]="CAP",
								["taskSelected"]=true,
								["tasks"]=
								{
								},
								["uncontrolled"]=false,
								["units"]=
								{
									[1]=
									{
										["AddPropAircraft"]=
										{
											["InnerBoard"]=0,
											["OuterBoard"]=0
										},
										["Radio"]=
										{
											[1]=
											{
												["channels"]=
												{
													[1]=251,
													[10]=262,
													[11]=259,
													[12]=268,
													[13]=269,
													[14]=260,
													[15]=263,
													[16]=261,
													[17]=267,
													[18]=251,
													[19]=253,
													[2]=264,
													[20]=266,
													[3]=265,
													[4]=256,
													[5]=254,
													[6]=250,
													[7]=270,
													[8]=257,
													[9]=255
												}
											},
											[2]=
											{
												["channels"]=
												{
													[1]=305,
													[10]=262,
													[11]=259,
													[12]=268,
													[13]=269,
													[14]=260,
													[15]=263,
													[16]=261,
													[17]=267,
													[18]=251,
													[19]=253,
													[2]=264,
													[20]=266,
													[3]=265,
													[4]=256,
													[5]=254,
													[6]=250,
													[7]=270,
													[8]=257,
													[9]=255
												}
											}
										},
										["alt"]=0,
										["alt_type"]="BARO",
										["callsign"]=
										{
											[1]=1,
											[2]=1,
											[3]=1,
											["name"]="Enfield11"
										},
										["hardpoint_racks"]=true,
										["heading"]=1.2490457723983,
										["livery_id"]="VFA-37",
										["name"]="DictKey_Translation_8",
										["onboard_num"]="010",
										["payload"]=
										{
											["chaff"]=60,
											["flare"]=30,
											["fuel"]=4900,
											["gun"]=100,
											["pylons"]=
											{
												[1]=
												{
													["CLSID"]="{6CEB49FC-DED8-4DED-B053-E1F033FF72D3}"
												},
												[2]=
												{
													["CLSID"]="LAU-115_2*LAU-127_AIM-9M"
												},
												[3]=
												{
													["CLSID"]="{FPU_8A_FUEL_TANK}"
												},
												[4]=
												{
													["CLSID"]="{8D399DDA-FF81-4F14-904D-099B34FE7918}"
												},
												[5]=
												{
													["CLSID"]="{FPU_8A_FUEL_TANK}"
												},
												[6]=
												{
													["CLSID"]="{8D399DDA-FF81-4F14-904D-099B34FE7918}"
												},
												[7]=
												{
													["CLSID"]="{FPU_8A_FUEL_TANK}"
												},
												[8]=
												{
													["CLSID"]="LAU-115_2*LAU-127_AIM-9M"
												},
												[9]=
												{
													["CLSID"]="{6CEB49FC-DED8-4DED-B053-E1F033FF72D3}"
												}
											}
										},
										["psi"]=-1.2490457723983,
										["skill"]="Client",
										["speed"]=0,
										["type"]="FA-18C_hornet",
										["unitId"]=2,
										["x"]=-214496.46875,
										["y"]=412218.921875
									},
									[2]=
									{
										["AddPropAircraft"]=
										{
											["InnerBoard"]=0,
											["OuterBoard"]=0
										},
										["Radio"]=
										{
											[1]=
											{
												["channels"]=
												{
													[1]=251,
													[10]=262,
													[11]=259,
													[12]=268,
													[13]=269,
													[14]=260,
													[15]=263,
													[16]=261,
													[17]=267,
													[18]=251,
													[19]=253,
													[2]=264,
													[20]=266,
													[3]=265,
													[4]=256,
													[5]=254,
													[6]=250,
													[7]=270,
													[8]=257,
													[9]=255
												}
											},
											[2]=
											{
												["channels"]=
												{
													[1]=305,
													[10]=262,
													[11]=259,
													[12]=268,
													[13]=269,
													[14]=260,
													[15]=263,
													[16]=261,
													[17]=267,
													[18]=251,
													[19]=253,
													[2]=264,
													[20]=266,
													[3]=265,
													[4]=256,
													[5]=254,
													[6]=250,
													[7]=270,
													[8]=257,
													[9]=255
												}
											}
										},
										["alt"]=0,
										["alt_type"]="BARO",
										["callsign"]=
										{
											[1]=1,
											[2]=1,
											[3]=2,
											["name"]="Enfield12"
										},
										["hardpoint_racks"]=true,
										["heading"]=1.2490457723983,
										["livery_id"]="VFA-37",
										["name"]="DictKey_Translation_9",
										["onboard_num"]="010",
										["payload"]=
										{
											["chaff"]=60,
											["flare"]=30,
											["fuel"]=4900,
											["gun"]=100,
											["pylons"]=
											{
												[1]=
												{
													["CLSID"]="{6CEB49FC-DED8-4DED-B053-E1F033FF72D3}"
												},
												[2]=
												{
													["CLSID"]="LAU-115_2*LAU-127_AIM-9M"
												},
												[3]=
												{
													["CLSID"]="{FPU_8A_FUEL_TANK}"
												},
												[4]=
												{
													["CLSID"]="{8D399DDA-FF81-4F14-904D-099B34FE7918}"
												},
												[5]=
												{
													["CLSID"]="{FPU_8A_FUEL_TANK}"
												},
												[6]=
												{
													["CLSID"]="{8D399DDA-FF81-4F14-904D-099B34FE7918}"
												},
												[7]=
												{
													["CLSID"]="{FPU_8A_FUEL_TANK}"
												},
												[8]=
												{
													["CLSID"]="LAU-115_2*LAU-127_AIM-9M"
												},
												[9]=
												{
													["CLSID"]="{6CEB49FC-DED8-4DED-B053-E1F033FF72D3}"
												}
											}
										},
										["psi"]=-1.2490457723983,
										["skill"]="Client",
										["speed"]=0,
										["type"]="FA-18C_hornet",
										["unitId"]=3,
										["x"]=-214496.46875,
										["y"]=412228.921875
									},
									[3]=
									{
										["AddPropAircraft"]=
										{
											["InnerBoard"]=0,
											["OuterBoard"]=0
										},
										["Radio"]=
										{
											[1]=
											{
												["channels"]=
												{
													[1]=251,
													[10]=262,
													[11]=259,
													[12]=268,
													[13]=269,
													[14]=260,
													[15]=263,
													[16]=261,
													[17]=267,
													[18]=251,
													[19]=253,
													[2]=264,
													[20]=266,
													[3]=265,
													[4]=256,
													[5]=254,
													[6]=250,
													[7]=270,
													[8]=257,
													[9]=255
												}
											},
											[2]=
											{
												["channels"]=
												{
													[1]=305,
													[10]=262,
													[11]=259,
													[12]=268,
													[13]=269,
													[14]=260,
													[15]=263,
													[16]=261,
													[17]=267,
													[18]=251,
													[19]=253,
													[2]=264,
													[20]=266,
													[3]=265,
													[4]=256,
													[5]=254,
													[6]=250,
													[7]=270,
													[8]=257,
													[9]=255
												}
											}
										},
										["alt"]=0,
										["alt_type"]="BARO",
										["callsign"]=
										{
											[1]=1,
											[2]=1,
											[3]=3,
											["name"]="Enfield13"
										},
										["hardpoint_racks"]=true,
										["heading"]=1.2490457723983,
										["livery_id"]="VFA-37",
										["name"]="DictKey_Translation_10",
										["onboard_num"]="010",
										["payload"]=
										{
											["chaff"]=60,
											["flare"]=30,
											["fuel"]=4900,
											["gun"]=100,
											["pylons"]=
											{
												[1]=
												{
													["CLSID"]="{6CEB49FC-DED8-4DED-B053-E1F033FF72D3}"
												},
												[2]=
												{
													["CLSID"]="LAU-115_2*LAU-127_AIM-9M"
												},
												[3]=
												{
													["CLSID"]="{FPU_8A_FUEL_TANK}"
												},
												[4]=
												{
													["CLSID"]="{8D399DDA-FF81-4F14-904D-099B34FE7918}"
												},
												[5]=
												{
													["CLSID"]="{FPU_8A_FUEL_TANK}"
												},
												[6]=
												{
													["CLSID"]="{8D399DDA-FF81-4F14-904D-099B34FE7918}"
												},
												[7]=
												{
													["CLSID"]="{FPU_8A_FUEL_TANK}"
												},
												[8]=
												{
													["CLSID"]="LAU-115_2*LAU-127_AIM-9M"
												},
												[9]=
												{
													["CLSID"]="{6CEB49FC-DED8-4DED-B053-E1F033FF72D3}"
												}
											}
										},
										["psi"]=-1.2490457723983,
										["skill"]="Client",
										["speed"]=0,
										["type"]="FA-18C_hornet",
										["unitId"]=4,
										["x"]=-214506.46875,
										["y"]=412218.921875
									},
									[4]=
									{
										["AddPropAircraft"]=
										{
											["InnerBoard"]=0,
											["OuterBoard"]=0
										},
										["Radio"]=
										{
											[1]=
											{
												["channels"]=
												{
													[1]=251,
													[10]=262,
													[11]=259,
													[12]=268,
													[13]=269,
													[14]=260,
													[15]=263,
													[16]=261,
													[17]=267,
													[18]=251,
													[19]=253,
													[2]=264,
													[20]=266,
													[3]=265,
													[4]=256,
													[5]=254,
													[6]=250,
													[7]=270,
													[8]=257,
													[9]=255
												}
											},
											[2]=
											{
												["channels"]=
												{
													[1]=305,
													[10]=262,
													[11]=259,
													[12]=268,
													[13]=269,
													[14]=260,
													[15]=263,
													[16]=261,
													[17]=267,
													[18]=251,
													[19]=253,
													[2]=264,
													[20]=266,
													[3]=265,
													[4]=256,
													[5]=254,
													[6]=250,
													[7]=270,
													[8]=257,
													[9]=255
												}
											}
										},
										["alt"]=0,
										["alt_type"]="BARO",
										["callsign"]=
										{
											[1]=1,
											[2]=1,
											[3]=4,
											["name"]="Enfield14"
										},
										["hardpoint_racks"]=true,
										["heading"]=1.2490457723983,
										["livery_id"]="VFA-37",
										["name"]="DictKey_Translation_11",
										["onboard_num"]="010",
										["payload"]=
										{
											["chaff"]=60,
											["flare"]=30,
											["fuel"]=4900,
											["gun"]=100,
											["pylons"]=
											{
												[1]=
												{
													["CLSID"]="{6CEB49FC-DED8-4DED-B053-E1F033FF72D3}"
												},
												[2]=
												{
													["CLSID"]="LAU-115_2*LAU-127_AIM-9M"
												},
												[3]=
												{
													["CLSID"]="{FPU_8A_FUEL_TANK}"
												},
												[4]=
												{
													["CLSID"]="{8D399DDA-FF81-4F14-904D-099B34FE7918}"
												},
												[5]=
												{
													["CLSID"]="{FPU_8A_FUEL_TANK}"
												},
												[6]=
												{
													["CLSID"]="{8D399DDA-FF81-4F14-904D-099B34FE7918}"
												},
												[7]=
												{
													["CLSID"]="{FPU_8A_FUEL_TANK}"
												},
												[8]=
												{
													["CLSID"]="LAU-115_2*LAU-127_AIM-9M"
												},
												[9]=
												{
													["CLSID"]="{6CEB49FC-DED8-4DED-B053-E1F033FF72D3}"
												}
											}
										},
										["psi"]=-1.2490457723983,
										["skill"]="Client",
										["speed"]=0,
										["type"]="FA-18C_hornet",
										["unitId"]=5,
										["x"]=-214506.46875,
										["y"]=412228.921875
									}
								},
								["x"]=-214496.46875,
								["y"]=412218.921875
							},
							[2]=
							{
								["communication"]=true,
								["frequency"]=251,
								["groupId"]=4,
								["hidden"]=false,
								["modulation"]=0,
								["name"]="DictKey_Translation_19",
								["radioSet"]=false,
								["route"]=
								{
									["points"]=
									{
										[1]=
										{
											["ETA"]=0,
											["ETA_locked"]=true,
											["action"]="Turning Point",
											["alt"]=9144.0,
											["alt_type"]="BARO",
											["formation_template"]="",
											["name"]="",
											["properties"]=
											{
												["angle"]=0,
												["scale"]=0,
												["steer"]=2,
												["vangle"]=0,
												["vnav"]=0
											},
											["speed"]=256.9722222222222,
											["speed_locked"]=true,
											["task"]=
											{
												["id"]="ComboTask",
												["params"]=
												{
													["tasks"]=
													{
														[1]=
														{
															["auto"]=true,
															["enabled"]=true,
															["id"]="AWACS",
															["number"]=1,
															["params"]=
															{
															}
														},
														[2]=
														{
															["auto"]=false,
															["enabled"]=true,
															["id"]="WrappedAction",
															["number"]=2,
															["params"]=
															{
																["action"]=
																{
																	["id"]="EPLRS",
																	["params"]=
																	{
																		["groupId"]=2,
																		["value"]=true
																	}
																}
															}
														},
														[3]=
														{
															["auto"]=false,
															["enabled"]=true,
															["id"]="WrappedAction",
															["number"]=3,
															["params"]=
															{
																["action"]=
																{
																	["id"]="EPLRS",
																	["params"]=
																	{
																		["groupId"]=1,
																		["value"]=true
																	}
																}
															}
														}
													}
												}
											},
											["type"]="Turning Point",
											["x"]=-144496.46875,
											["y"]=540218.921875
										},
										[2]=
										{
											["ETA"]=0,
											["ETA_locked"]=false,
											["action"]="Turning Point",
											["alt"]=9144.0,
											["alt_type"]="BARO",
											["formation_template"]="",
											["name"]="",
											["properties"]=
											{
												["angle"]=0,
												["scale"]=0,
												["steer"]=2,
												["vangle"]=0,
												["vnav"]=0
											},
											["speed"]=256.9722222222222,
											["speed_locked"]=true,
											["task"]=
											{
												["id"]="ComboTask",
												["params"]=
												{
													["tasks"]=
													{
														[1]=
														{
															["auto"]=false,
															["enabled"]=true,
															["id"]="WrappedAction",
															["number"]=1,
															["params"]=
															{
																["action"]=
																{
																	["id"]="SetFrequency",
																	["params"]=
																	{
																		["frequency"]=140000000,
																		["modulation"]=0
																	}
																}
															}
														}
													}
												}
											},
											["type"]="Turning Point",
											["x"]=-144496.46875,
											["y"]=541218.921875
										},
										[3]=
										{
											["ETA"]=0,
											["ETA_locked"]=false,
											["action"]="Turning Point",
											["alt"]=9144.0,
											["alt_type"]="BARO",
											["formation_template"]="",
											["name"]="",
											["properties"]=
											{
												["angle"]=0,
												["scale"]=0,
												["steer"]=2,
												["vangle"]=0,
												["vnav"]=0
											},
											["speed"]=256.9722222222222,
											["speed_locked"]=true,
											["task"]=
											{
												["id"]="ComboTask",
												["params"]=
												{
													["tasks"]=
													{
														[1]=
														{
															["auto"]=false,
															["enabled"]=true,
															["id"]="Orbit",
															["number"]=1,
															["params"]=
															{
																["altitude"]=9144.0,
																["pattern"]="Race-Track",
																["speed"]=256.97222222222223,
																["speedEdited"]=true
															}
														}
													}
												}
											},
											["type"]="Turning Point",
											["x"]=-144496.46875,
											["y"]=542218.921875
										},
										[4]=
										{
											["ETA"]=0,
											["ETA_locked"]=false,
											["action"]="Turning Point",
											["alt"]=9144.0,
											["alt_type"]="BARO",
											["formation_template"]="",
											["name"]="",
											["properties"]=
											{
												["angle"]=0,
												["scale"]=0,
												["steer"]=2,
												["vangle"]=0,
												["vnav"]=0
											},
											["speed"]=256.9722222222222,
											["speed_locked"]=true,
											["task"]=
											{
												["id"]="ComboTask",
												["params"]=
												{
													["tasks"]=
													{
													}
												}
											},
											["type"]="Turning Point",
											["x"]=-144496.46875,
											["y"]=622218.921875
										}
									}
								},
								["start_time"]=0,
								["task"]="AWACS",
								["taskSelected"]=true,
								["tasks"]=
								{
								},
								["uncontrolled"]=false,
								["units"]=
								{
									[1]=
									{
										["alt"]=9144.0,
										["alt_type"]="BARO",
										["callsign"]=
										{
											[1]=1,
											[2]=1,
											[3]=1,
											["name"]="Overlord11"
										},
										["hardpoint_racks"]=true,
										["heading"]=1.5707963267949,
										["livery_id"]="nato",
										["name"]="DictKey_Translation_20",
										["onboard_num"]="010",
										["payload"]=
										{
											["chaff"]=120,
											["flare"]=60,
											["fuel"]=58500.0,
											["gun"]=100,
											["pylons"]=
											{
											}
										},
										["psi"]=-1.5707963267949,
										["skill"]="Average",
										["speed"]=256.9722222222222,
										["type"]="E-3A",
										["unitId"]=12,
										["x"]=-144496.46875,
										["y"]=540218.921875
									}
								},
								["x"]=-144496.46875,
								["y"]=540218.921875
							}
						}
					},
					["ship"]=
					{
						["group"]=
						{
							[1]=
							{
								["groupId"]=1,
								["hidden"]=false,
								["name"]="DictKey_Translation_5",
								["route"]=
								{
									["points"]=
									{
										[1]=
										{
											["ETA"]=0,
											["ETA_locked"]=true,
											["action"]="Turning Point",
											["alt"]=0,
											["alt_type"]="BARO",
											["formation_template"]="",
											["name"]="",
											["speed"]=5.5555555555556,
											["speed_locked"]=true,
											["task"]=
											{
												["id"]="ComboTask",
												["params"]=
												{
													["tasks"]=
													{
														[1]=
														{
															["auto"]=false,
															["enabled"]=true,
															["id"]="WrappedAction",
															["number"]=1,
															["params"]=
															{
																["action"]=
																{
																	["id"]="ActivateICLS",
																	["params"]=
																	{
																		["channel"]=5,
																		["type"]=131584,
																		["unitId"]=1
																	}
																}
															}
														},
														[2]=
														{
															["auto"]=false,
															["enabled"]=true,
															["id"]="WrappedAction",
															["number"]=2,
															["params"]=
															{
																["action"]=
																{
																	["id"]="ActivateBeacon",
																	["params"]=
																	{
																		["bearing"]=true,
																		["callsign"]="STN",
																		["channel"]=69,
																		["frequency"]=1156000000,
																		["modeChannel"]="X",
																		["system"]=3,
																		["type"]=4,
																		["unitId"]=1
																	}
																}
															}
														}
													}
												}
											},
											["type"]="Turning Point",
											["x"]=-214496.46875,
											["y"]=412218.921875
										},
										[2]=
										{
											["ETA"]=0,
											["ETA_locked"]=false,
											["action"]="Turning Point",
											["alt"]=0,
											["alt_type"]="BARO",
											["formation_template"]="",
											["name"]="",
											["speed"]=5.5555555555556,
											["speed_locked"]=true,
											["task"]=
											{
												["id"]="ComboTask",
												["params"]=
												{
													["tasks"]=
													{
													}
												}
											},
											["type"]="Turning Point",
											["x"]=-214496.46875,
											["y"]=312218.921875
										},
										[3]=
										{
											["ETA"]=0,
											["ETA_locked"]=false,
											["action"]="Turning Point",
											["alt"]=0,
											["alt_type"]="BARO",
											["formation_template"]="",
											["name"]="",
											["speed"]=5.5555555555556,
											["speed_locked"]=true,
											["task"]=
											{
												["id"]="ComboTask",
												["params"]=
												{
													["tasks"]=
													{
													}
												}
											},
											["type"]="Turning Point",
											["x"]=-244496.46875,
											["y"]=312218.921875
										},
										[4]=
										{
											["ETA"]=0,
											["ETA_locked"]=false,
											["action"]="Turning Point",
											["alt"]=0,
											["alt_type"]="BARO",
											["formation_template"]="",
											["name"]="",
											["speed"]=5.5555555555556,
											["speed_locked"]=true,
											["task"]=
											{
												["id"]="ComboTask",
												["params"]=
												{
													["tasks"]=
													{
													}
												}
											},
											["type"]="Turning Point",
											["x"]=-244496.46875,
											["y"]=412218.921875
										}
									}
								},
								["start_time"]=0,
								["taskSelected"]=true,
								["tasks"]=
								{
								},
								["units"]=
								{
									[1]=
									{
										["heading"]=4.7123889803847,
										["name"]="DictKey_Translation_6",
										["skill"]="Average",
										["transportable"]=
										{
											["randomTransportable"]=false
										},
										["type"]="Stennis",
										["unitId"]=1,
										["x"]=-214496.46875,
										["y"]=412218.921875
									}
								},
								["visible"]=false,
								["x"]=-214496.46875,
								["y"]=412218.921875
							}
						}
					}
				},
				[2]=
				{
					["id"]=11,
					["name"]="Belgium"
				},
				[3]=
				{
					["id"]=8,
					["name"]="Canada"
				},
				[4]=
				{
					["id"]=28,
					["name"]="Croatia"
				},
				[5]=
				{
					["id"]=26,
					["name"]="Czech Republic"
				},
				[6]=
				{
					["id"]=13,
					["name"]="Denmark"
				},
				[7]=
				{
					["id"]=5,
					["name"]="France"
				},
				[8]=
				{
					["id"]=16,
					["name"]="Georgia"
				},
				[9]=
				{
					["id"]=6,
					["name"]="Germany"
				}
			},
			["name"]="blue",
			["nav_points"]=
			{
			}
		},
		["red"]=
		{
			["bullseye"]=
			{
				["x"]=11557,
				["y"]=371700
			},
			["country"]=
			{
				[1]=
				{
					["id"]=18,
					["name"]="Abkhazia"
				},
				[10]=
				{
					["id"]=47,
					["name"]="Syria"
				},
				[11]=
				{
					["id"]=1,
					["name"]="Ukraine"
				},
				[2]=
				{
					["id"]=24,
					["name"]="Belarus"
				},
				[3]=
				{
					["id"]=27,
					["name"]="China"
				},
				[4]=
				{
					["id"]=34,
					["name"]="Iran"
				},
				[5]=
				{
					["id"]=37,
					["name"]="Kazakhstan"
				},
				[6]=
				{
					["id"]=38,
					["name"]="North Korea"
				},
				[7]=
				{
					["id"]=0,
					["name"]="Russia",
					["vehicle"]=
					{
						["group"]=
						{
							[1]=
							{
								["groupId"]=3,
								["hidden"]=false,
								["name"]="DictKey_Translation_12",
								["route"]=
								{
									["points"]=
									{
										[1]=
										{
											["ETA"]=0,
											["ETA_locked"]=true,
											["action"]="Off Road",
											["alt"]=0,
											["alt_type"]="BARO",
											["formation_template"]="",
											["name"]="",
											["speed"]=0.0,
											["speed_locked"]=true,
											["task"]=
											{
												["id"]="ComboTask",
												["params"]=
												{
													["tasks"]=
													{
													}
												}
											},
											["type"]="Turning Point",
											["x"]=-164291.91888435048,
											["y"]=462819.5779515109
										}
									},
									["spans"]=
									{
									}
								},
								["start_time"]=0,
								["task"]="Ground Nothing",
								["taskSelected"]=true,
								["tasks"]=
								{
								},
								["units"]=
								{
									[1]=
									{
										["heading"]=0.0515901525813,
										["name"]="DictKey_Translation_13",
										["playerCanDrive"]=false,
										["skill"]="Average",
										["transportable"]=
										{
											["randomTransportable"]=false
										},
										["type"]="SNR_75V",
										["unitId"]=6,
										["x"]=-164291.91888435048,
										["y"]=462819.5779515109
									},
									[2]=
									{
										["heading"]=0.0515901525813,
										["name"]="DictKey_Translation_14",
										["playerCanDrive"]=false,
										["skill"]="Average",
										["transportable"]=
										{
											["randomTransportable"]=false
										},
										["type"]="S_75M_Volhov",
										["unitId"]=7,
										["x"]=-164241.98540818994,
										["y"]=462822.15631504677
									},
									[3]=
									{
										["heading"]=1.3082272140172,
										["name"]="DictKey_Translation_15",
										["playerCanDrive"]=false,
										["skill"]="Average",
										["transportable"]=
										{
											["randomTransportable"]=false
										},
										["type"]="S_75M_Volhov",
										["unitId"]=8,
										["x"]=-164278.94076107084,
										["y"]=462867.86426754494
									},
									[4]=
									{
										["heading"]=2.5648642754531,
										["name"]="DictKey_Translation_16",
										["playerCanDrive"]=false,
										["skill"]="Average",
										["transportable"]=
										{
											["randomTransportable"]=false
										},
										["type"]="S_75M_Volhov",
										["unitId"]=9,
										["x"]=-164333.83143921403,
										["y"]=462846.8421724756
									},
									[5]=
									{
										["heading"]=3.821501336889,
										["name"]="DictKey_Translation_17",
										["playerCanDrive"]=false,
										["skill"]="Average",
										["transportable"]=
										{
											["randomTransportable"]=false
										},
										["type"]="S_75M_Volhov",
										["unitId"]=10,
										["x"]=-164330.80039109115,
										["y"]=462788.1418507098
									},
									[6]=
									{
										["heading"]=5.078138398325,
										["name"]="DictKey_Translation_18",
										["playerCanDrive"]=false,
										["skill"]="Average",
										["transportable"]=
										{
											["randomTransportable"]=false
										},
										["type"]="S_75M_Volhov",
										["unitId"]=11,
										["x"]=-164274.03642218647,
										["y"]=462772.8851517774
									}
								},
								["visible"]=false,
								["x"]=-164291.91888435048,
								["y"]=462819.5779515109
							}
						}
					}
				},
				[8]=
				{
					["id"]=43,
					["name"]="Serbia"
				},
				[9]=
				{
					["id"]=19,
					["name"]="South Ossetia"
				}
			},
			["name"]="red",
			["nav_points"]=
			{
			}
		}
	},
	["coalitions"]=
	{
		["blue"]=
		{
			[1]=2,
			[10]=12,
			[11]=13,
			[12]=15,
			[13]=16,
			[14]=20,
			[15]=21,
			[16]=26,
			[17]=28,
			[18]=40,
			[19]=45,
			[2]=3,
			[3]=4,
			[4]=5,
			[5]=6,
			[6]=8,
			[7]=9,
			[8]=10,
			[9]=11
		},
		["neutral"]=
		{
			[1]=32,
			[10]=46,
			[11]=17,
			[12]=22,
			[13]=23,
			[14]=25,
			[15]=29,
			[16]=30,
			[17]=31,
			[2]=33,
			[3]=35,
			[4]=36,
			[5]=7,
			[6]=39,
			[7]=41,
			[8]=42,
			[9]=44
		},
		["red"]=
		{
			[1]=0,
			[10]=24,
			[11]=27,
			[2]=1,
			[3]=34,
			[4]=37,
			[5]=38,
			[6]=43,
			[7]=47,
			[8]=18,
			[9]=19
		}
	},
	["currentKey"]=0,
	["date"]=
	{
		["Day"]=1,
		["Month"]=6,
		["Year"]=2011
	},
	["descriptionBlueTask"]="DictKey_Translation_2",
	["descriptionRedTask"]="DictKey_Translation_3",
	["descriptionText"]="DictKey_Translation_1",
	["failures"]=
	{
	},
	["forcedOptions"]=
	{
	},
	["goals"]=
	{
	},
	["groundControl"]=
	{
		["isPilotControlVehicles"]=false,
		["roles"]=
		{
			["artillery_commander"]=
			{
				["blue"]=0,
				["neutrals"]=0,
				["red"]=0
			},
			["forward_observer"]=
			{
				["blue"]=0,
				["neutrals"]=0,
				["red"]=0
			},
			["instructor"]=
			{
				["blue"]=0,
				["neutrals"]=0,
				["red"]=0
			},
			["observer"]=
			{
				["blue"]=0,
				["neutrals"]=0,
				["red"]=0
			}
		}
	},
	["map"]=
	{
		["centerX"]=-255714.28571428,
		["centerY"]=680571.42857143,
		["zoom"]=1000000
	},
	["maxDictId"]=20,
	["pictureFileNameB"]=
	{
	},
	["pictureFileNameR"]=
	{
	},
	["resourceCounter"]=
	{
	},
	["result"]=
	{
		["blue"]=
		{
			["actions"]=
			{
			},
			["conditions"]=
			{
			},
			["func"]=
			{
			}
		},
		["offline"]=
		{
			["actions"]=
			{
			},
			["conditions"]=
			{
			},
			["func"]=
			{
			}
		},
		["red"]=
		{
			["actions"]=
			{
			},
			["conditions"]=
			{
			},
			["func"]=
			{
			}
		},
		["total"]=0
	},
	["sortie"]="DictKey_Translation_4",
	["start_time"]=43200,
	["theatre"]="Caucasus",
	["trig"]=
	{
		["actions"]=
		{
		},
		["conditions"]=
		{
		},
		["customStartup"]=
		{
		},
		["events"]=
		{
		},
		["flag"]=
		{
		},
		["func"]=
		{
		},
		["funcStartup"]=
		{
		}
	},
	["triggers"]=
	{
		["zones"]=
		{
		}
	},
	["trigrules"]=
	{
	},
	["usedModules"]=
	{
		["./CoreMods/aircraft/MQ-9 Reaper"]=true,
		["A-10A by Eagle Dynamics"]=true,
		["A-10C Warthog by Eagle Dynamics"]=true,
		["Bf 109 K-4 by Eagle Dynamics"]=true,
		["C-101 Aviojet"]=true,
		["C-101 Aviojet by AvioDev"]=true,
		["Caucasus"]=true,
		["Combined Arms by Eagle Dynamics"]=true,
		["F-15C"]=true,
		["F-5E/E-3 by Belsimtek"]=true,
		["F-86F Sabre AI by Eagle Dynamics"]=true,
		["F-86F Sabre by Belsimtek"]=true,
		["FW-190D9 Dora by Eagle Dynamics"]=true,
		["Flaming Cliffs by Eagle Dynamics"]=true,
		["Hawk T.1A AI by VEAO Simulations"]=true,
		["Hawk T.1A by VEAO Simulations"]=true,
		["Ka-50 Black Shark by Eagle Dynamics"]=true,
		["L-39C"]=true,
		["L-39C/ZA by Eagle Dynamics"]=true,
		["M-2000C AI by RAZBAM Sims"]=true,
		["M-2000C by RAZBAM Sims"]=true,
		["Mi-8MTV2 Hip by Belsimtek"]=true,
		["MiG-15bis AI by Eagle Dynamics"]=true,
		["MiG-15bis by Belsimtek"]=true,
		["MiG-21Bis AI by Leatherneck Simulations"]=true,
		["MiG-21Bis by Leatherneck Simulations"]=true,
		["P-51D Mustang by Eagle Dynamics"]=true,
		["Su-25A by Eagle Dynamics"]=true,
		["Su-25T by Eagle Dynamics"]=true,
		["Su-27 Flanker by Eagle Dynamics"]=true,
		["TF-51D Mustang by Eagle Dynamics"]=true,
		["UH-1H Huey by Belsimtek"]=true,
		["World War II AI Units by Eagle Dynamics"]=true
	},
	["version"]=16,
	["weather"]=
	{
		["atmosphere_type"]=0,
		["clouds"]=
		{
			["base"]=300,
			["density"]=0,
			["iprecptns"]=0,
			["thickness"]=200
		},
		["cyclones"]=
		{
		},
		["dust_density"]=0,
		["enable_dust"]=false,
		["enable_fog"]=false,
		["fog"]=
		{
			["density"]=7,
			["thickness"]=0,
			["visibility"]=25
		},
		["groundTurbulence"]=0,
		["name"]="Summer, clean sky",
		["qnh"]=760,
		["season"]=
		{
			["temperature"]=20
		},
		["type_weather"]=0,
		["visibility"]=
		{
			["distance"]=80000
		},
		["wind"]=
		{
			["at2000"]=
			{
				["dir"]=0,
				["speed"]=0
			},
			["at8000"]=
			{
				["dir"]=0,
				["speed"]=0
			},
			["atGround"]=
			{
				["dir"]=0,
				["speed"]=0
			}
		}
	}
}