# This is a basic workflow to help you get started with Actions

name: Build exe

# Controls when the action will run.
on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: Set up ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Set up Node
        uses: actions/setup-node@v1
        with:
          node-version: "16"

      - name: Install Poetry
        uses: snok/install-poetry@v1

      - name: Install dependencies
        run: poetry install --no-interaction --no-root

      - name: Set version for UI
        run: |
          ./env/scripts/activate
          python ./scripts/gen_version.py
          Copy-Item .\version.json .\frontend\src\data\ -Force

      - name: Build frontend
        run: |
          cd ./frontend
          yarn
          $env:CI="false"
          yarn build
          Copy-Item -r .\build ..\tauntaun_live_editor\data\client

      - name: Build binaries
        run: poetry run pyinstaller.exe --noconfirm tauntaun_live_editor.spec

      - uses: actions/upload-artifact@v2
        with:
          name: tauntaun_live_editor_${{github.sha}}
          path: dist/tauntaun_live_editor
